name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          # pin Node to 18 for compatibility with repo dependencies
          node-version: '18'
      - name: Install dependencies
        run: npm ci --no-audit --no-fund --no-optional
      - name: Linter the code
        run: npm run eslint
      - name: Run built
        run: npm run build
      - name: Run tests
        run: npm test
      - name: EndToEnd tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: 'http://localhost:8080'
